<?php
declare(strict_types=1);require_once __DIR__.'/lib/bootstrap.php';
$origin=$_SERVER['HTTP_ORIGIN']??'';$allowed=['http://localhost:5173','http://127.0.0.1:5173'];if(in_array($origin,$allowed,true))header('Access-Control-Allow-Origin: '.$origin);header('Vary: Origin');header('Access-Control-Allow-Methods: GET, POST, OPTIONS');header('Access-Control-Allow-Headers: Content-Type');header('Content-Type: application/json; charset=utf-8');
if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}if($_SERVER['REQUEST_METHOD']==='GET'){echo json_encode(['success'=>true,'products'=>products()]);exit;}if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'message'=>'Method not allowed']);exit;}
$input=json_decode((string)file_get_contents('php://input'),true);$name=trim((string)($input['name']??''));if(!is_array($input)||$name===''){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Product name is required']);exit;}
function store_image(string $data):string{if(!preg_match('#^data:image/(jpeg|png|webp);base64,(.+)$#s',$data,$m))return '';$bytes=base64_decode($m[2],true);if($bytes===false||strlen($bytes)>8*1024*1024)return '';$ext=$m[1]==='jpeg'?'jpg':$m[1];if(!is_dir(UPLOAD_DIR))mkdir(UPLOAD_DIR,0775,true);$file=bin2hex(random_bytes(10)).'.'.$ext;return file_put_contents(UPLOAD_DIR.'/'.$file,$bytes)!==false?'assets/img/products/'.$file:'';}
function store_pdf(string $data):string{if(!preg_match('#^data:application/pdf;base64,(.+)$#s',$data,$m))return '';$bytes=base64_decode($m[1],true);if($bytes===false||strlen($bytes)>10*1024*1024)return '';$dir=APP_ROOT.'/assets/brochures';if(!is_dir($dir))mkdir($dir,0775,true);$file=bin2hex(random_bytes(10)).'.pdf';return file_put_contents($dir.'/'.$file,$bytes)!==false?'assets/brochures/'.$file:'';}
$store=read_store();$store['products']=is_array($store['products']??null)?$store['products']:[];$store['categories']=is_array($store['categories']??null)?$store['categories']:[];$slug=slugify((string)($input['slug']??$name));$existingIndex=null;foreach($store['products'] as $index=>$savedProduct){if(($savedProduct['slug']??'')===$slug){$existingIndex=$index;break;}}
$category=trim((string)($input['category']??''));if($category!==''&&!in_array($category,$store['categories'],true))$store['categories'][]=$category;$gallery=[];foreach((array)($input['gallery']??[]) as $raw){$saved=store_image((string)$raw);if($saved)$gallery[]=$saved;}$showcase=[];foreach((array)($input['showcase_cards']??[]) as $card){$cardImage=store_image((string)($card['image']??''));$cardTitle=trim((string)($card['title']??''));$cardVideo=trim((string)($card['videoUrl']??''));if($cardTitle===''&&$cardImage===''&&$cardVideo==='')continue;$showcase[]=['title'=>$cardTitle,'description'=>trim((string)($card['description']??'')),'type'=>($card['type']??'image')==='video'?'video':'image','video_url'=>$cardVideo,'image'=>$cardImage,'alt'=>trim((string)($card['alt']??''))];}
$product=['id'=>'product-'.bin2hex(random_bytes(6)),'name'=>$name,'slug'=>$slug,'category'=>$category,'group'=>trim((string)($input['group']??'')),'short_description'=>trim((string)($input['short_description']??'')),'description'=>(string)($input['description']??''),'hero_heading'=>trim((string)($input['hero_heading']??'')),'hero_subheading'=>trim((string)($input['hero_subheading']??'')),'image'=>store_image((string)($input['image']??''))?:'assets/img/machines/Rotogravure-Printing-Machine.webp','gallery'=>$gallery,'showcase_cards'=>$showcase,'video_url'=>trim((string)($input['video_url']??'')),'video_heading'=>trim((string)($input['video_heading']??'')),'video_description'=>trim((string)($input['video_description']??'')),'brochure'=>store_pdf((string)($input['brochure']??'')),'specifications'=>array_values((array)($input['specifications']??[])),'features'=>array_values(array_filter((array)($input['features']??[]),fn($row)=>trim((string)($row['title']??''))!=='')),'steps'=>array_values(array_filter((array)($input['steps']??[]),fn($row)=>trim((string)($row['title']??''))!=='')),'testimonials'=>array_values(array_filter((array)($input['testimonials']??[]),fn($row)=>trim((string)($row['name']??''))!=='')),'faqs'=>array_values(array_filter((array)($input['faqs']??[]),fn($row)=>trim((string)($row['question']??''))!=='')),'active'=>true,'featured'=>false,'position'=>count($store['products'])+1,'seo_title'=>$name.' | Mohindra Mechanical Works','seo_description'=>trim((string)($input['short_description']??'')),'seo_keywords'=>''];if($existingIndex!==null){$product['id']=$store['products'][$existingIndex]['id']??$product['id'];$product['position']=$store['products'][$existingIndex]['position']??$product['position'];$store['products'][$existingIndex]=$product;}else{$store['products'][]=$product;}
if(!write_store($store)){http_response_code(500);echo json_encode(['success'=>false,'message'=>'Product data could not be saved']);exit;}http_response_code(201);echo json_encode(['success'=>true,'product'=>$product]);
