const make = (category, names) =>
  names.map((name, i) => ({
    id: `${category.toLowerCase().replace(/\W+/g, "-")}-${i}`,
    name,
    category,
    slug: name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, ""),
    image: "/catalog-hero.png",
    description: `${name} engineered for reliable, high-quality industrial printing applications.`,
  }));
export const catalogGroups = [
  {
    title: "Rotogravure Printing Machine",
    products: make("Rotogravure Printing Machine", [
      "Gear Driven Rotogravure Printing Machine",
      "Servo Rotogravure Printing Machine",
      "Multi Colour Rotogravure Printing Machine",
      "Single Colour Rotogravure Printing Machine",
      "2 Colour Rotogravure Printing Machine",
      "3 Colour Rotogravure Printing Machine",
      "4 Colour Rotogravure Printing Machine",
      "5 Colour Rotogravure Printing Machine",
      "6 Colour Rotogravure Printing Machine",
      "7 Colour Rotogravure Printing Machine",
      "8 Colour Rotogravure Printing Machine",
      "9 Colour Rotogravure Printing Machine",
      "10 Colour Rotogravure Printing Machine",
      "Paper Rotogravure Printing Machine",
      "Kraft Paper Rotogravure Printing Machine",
      "Coated Paper Rotogravure Printing Machine",
      "Decorative Paper Rotogravure Printing Machine",
      "Thin Paper Rotogravure Printing Machine",
      "Specialty Paper Rotogravure Printing Machine",
      "Wallpaper Rotogravure Printing Machine",
      "Gift Paper Rotogravure Printing Machine",
      "Wrapping Paper Rotogravure Printing Machine",
      "Printed Paper Rotogravure Printing Machine",
    ]),
  },
  {
    title: "MLS Rotogravure Printing Machine",
    products: make("MLS Rotogravure Printing Machine", [
      "Servo MLS Rotogravure Printing Machine",
      "MLS Plastic Film Rotogravure Printing Machine",
      "MLS Flexible Film Rotogravure Printing Machine",
      "MLS BOPP Film Rotogravure Printing Machine",
      "MLS PET Film Rotogravure Printing Machine",
      "MLS CPP Film Rotogravure Printing Machine",
      "MLS PE Film Rotogravure Printing Machine",
      "MLS LDPE Film Rotogravure Printing Machine",
      "MLS HDPE Film Rotogravure Printing Machine",
      "MLS Polyester Film Rotogravure Printing Machine",
      "MLS Polypropylene Film Rotogravure Printing Machine",
    ]),
  },
  {
    title: "Shafted Rotogravure Printing Machine",
    products: make("Shafted Rotogravure Printing Machine", [
      "6 Colour Shafted Rotogravure Machine",
      "7 Colour Shafted Rotogravure Machine",
      "8 Colour Shafted Rotogravure Machine",
      "Shafted MLS Nylon Film Rotogravure Printing Machine",
      "Shafted MLS PVC Film Rotogravure Printing Machine",
      "Shafted MLS Shrink Film Rotogravure Printing Machine",
      "Shafted MLS Metallized Film Rotogravure Printing Machine",
      "Shafted MLS Laminated Film Rotogravure Printing Machine",
      "Shafted MLS Composite Film Rotogravure Printing Machine",
      "Shafted MLS Decorative Film Rotogravure Printing Machine",
      "Shafted MLS Industrial Film Rotogravure Printing Machine",
      "Shafted MLS Packaging Film Rotogravure Printing Machine",
      "Shafted MLS Flexible Packaging Film Rotogravure Printing Machine",
    ]),
  },
  {
    title: "Shaftless Rotogravure Printing Machine",
    products: make("Shaftless Rotogravure Printing Machine", [
      "8 Colour Shaftless Rotogravure Machine",
      "9 Colour Shaftless Rotogravure Machine",
      "10 Colour Shaftless Rotogravure Machine",
      "Shaftless MLS Reverse Printed Film Rotogravure Printing Machine",
      "Shaftless MLS Surface Printed Film Rotogravure Printing Machine",
      "Shaftless MLS Roll to Roll Film Rotogravure Printing Machine",
      "Shaftless MLS Multi Colour Film Rotogravure Printing Machine",
      "Shaftless MLS High Speed Film Rotogravure Printing Machine",
      "Shaftless MLS Automatic Film Rotogravure Printing Machine",
      "Shaftless MLS Film Rotogravure Printing Machine",
      "Shaftless MLS Pharmaceutical Film Rotogravure Printing Machine",
      "Shaftless MLS Food Packaging Film Rotogravure Printing Machine",
      "Shaftless MLS Industrial Packaging Film Rotogravure Printing Machine",
    ]),
  },
  {
    title: "Pharmaceutical Foil Rotogravure Printing Machine",
    products: make("Pharmaceutical Foil Rotogravure Printing Machine", [
      "Pharmaceutical Blister Foil Printing Machine",
      "Alu Alu Packaging Foil Printing Machine",
      "Aluminum Foil Printing Machine For Pharma",
      "Medicine Foil Printing Machine",
      "Blister Foil Printing Machine",
      "Pharma Packaging Printing Machine",
      "Pharma Blister Packing Printing Machine",
      "Pharma Strip Packing Foil Printing Machine",
      "Capsule Packaging Foil Printing Machine",
      "Pharmaceutical Aluminum Foil Printing Machine",
      "Automatic Pharmaceutical Foil Printing Machine",
      "High-Speed Blister Foil Printing Machine",
      "Industrial Pharma Foil Printing Machine",
      "PVC Film Printing Machine",
      "PVDC Coated Film Printing Machine",
      "Alu Alu Foil Printing Machine",
      "Cold Form Foil Printing Machine",
      "PET Film Printing Machine",
      "Polyester Film Printing Machine",
      "BOPP Film Printing Machine",
      "LDPE Film Printing Machine",
      "Polypropylene Printing Machine",
      "Laminated Foil Printing Machine",
      "Alu-Alu Blister Foil Printing Machine",
    ]),
  },
];
