import React,{useState}from'react';
import{Editor}from'@tinymce/tinymce-react';
import{ArrowLeft,Save,Eye,ImagePlus,Upload,Plus,Trash2,GripVertical,Heading2,AlignLeft,Settings2,CircleHelp,Video,FileText,FolderTree,Boxes,Search,Check,Share2,Code2,BarChart3,Play,MonitorPlay}from'lucide-react';

const Field=({label,required,children,hint})=><label className="form-field"><span>{label}{required&&<em>*</em>}</span>{children}{hint&&<small>{hint}</small>}</label>;

function ProductCards(){const[cards,setCards]=useState([{title:'Printed Food Packaging Films',type:'image',videoUrl:''}]);const addCard=()=>setCards([...cards,{title:'',type:'image',videoUrl:''}]);const update=(i,key,value)=>setCards(cards.map((c,n)=>n===i?{...c,[key]:value}:c));return <section className="form-card"><div className="form-card-title"><MonitorPlay/><div><h3>Website product cards</h3><p>Cards displayed in the finished-products, applications or media section</p></div><button className="section-add" onClick={addCard}><Plus/> Add card</button></div><div className="web-card-builder">{cards.map((card,i)=><div className="web-card-edit" key={i}><div className="web-card-preview"><div className="card-media-preview">{card.type==='video'?<><Video/><span className="play-badge"><Play/></span></>:<ImagePlus/>}<input type="file" accept="image/*"/></div><strong>{card.title||'Card title preview'}</strong></div><div className="web-card-fields"><Field label="Card title" required><input value={card.title} onChange={e=>update(i,'title',e.target.value)} placeholder="Printed Film & Foil Rolls"/></Field><div className="form-grid two"><Field label="Card type"><select value={card.type} onChange={e=>update(i,'type',e.target.value)}><option value="image">Image card</option><option value="video">YouTube video card</option></select></Field><Field label="Display order"><input type="number" min="1" defaultValue={i+1}/></Field></div>{card.type==='video'&&<Field label="YouTube URL" required><input value={card.videoUrl} onChange={e=>update(i,'videoUrl',e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/></Field>}<Field label="Image alt text" required><input placeholder="Describe the finished product shown"/></Field><button className="remove-card" onClick={()=>setCards(cards.filter((_,n)=>n!==i))}><Trash2/> Remove card</button></div></div>)}</div><div className="card-help"><Check/><p><b>Frontend-ready section</b><span>Published cards can be rendered as a responsive slider. Video cards use the uploaded thumbnail and open the saved YouTube video.</span></p></div></section>}

export default function ProductForm({onBack,onNotify=()=>{},onPublished=()=>{}}){
 const[name,setName]=useState('');
 const[description,setDescription]=useState('');
 const previewProduct=()=>{const productName=name||document.querySelector('.form-main .form-card input')?.value||'Industrial Printing Machine';localStorage.setItem('mmw-product-preview',JSON.stringify({name:productName,description:description||'<h2>Product description preview</h2><p>Add content in the TinyMCE editor to see it rendered here.</p>'}));window.open('/?preview=product','_blank','noopener,noreferrer')};
 const[specs,setSpecs]=useState([{name:'Printing Width',value:''},{name:'Printing Speed',value:''}]);
 const[faqs,setFaqs]=useState([{question:'',answer:''}]);
 const[tab,setTab]=useState('content');
 const addSpec=()=>setSpecs([...specs,{name:'',value:''}]);
 const updateSpec=(i,key,value)=>setSpecs(specs.map((s,n)=>n===i?{...s,[key]:value}:s));
 const removeSpec=i=>setSpecs(specs.filter((_,n)=>n!==i));
 const addFaq=()=>setFaqs([...faqs,{question:'',answer:''}]);
 const updateFaq=(i,key,value)=>setFaqs(faqs.map((f,n)=>n===i?{...f,[key]:value}:f));
 return <div className="product-form-page animate-in">
  <div className="form-page-head"><div><button className="back-btn" onClick={onBack}><ArrowLeft/> Products</button><h1>Add new product</h1><p>Create product content, media, specifications and SEO.</p></div><div className="form-head-actions"><button className="btn secondary" onClick={previewProduct}><Eye/> Preview frontend</button><button className="btn secondary" onClick={()=>{localStorage.setItem('mmw-product-draft',JSON.stringify({name,description}));onNotify('Draft saved','Product draft saved locally for testing.')}}><Save/> Save draft</button><button className="btn primary" onClick={()=>{localStorage.setItem('mmw-product-preview',JSON.stringify({name:name||'Industrial Printing Machine',description}));onPublished(name)}}><Check/> Publish product</button></div></div>
  <div className="form-tabs">{[['content','Content'],['media','Media'],['seo','SEO & URL']].map(([id,name])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{name}</button>)}</div>
  {tab==='content'&&<div className="form-layout"><div className="form-main">
   <section className="form-card"><div className="form-card-title"><Heading2/><div><h3>Basic information</h3><p>Product identity and catalogue structure</p></div></div><div className="form-grid two"><Field label="Product name" required><input placeholder="e.g. Servo Rotogravure Printing Machine"/></Field><Field label="URL slug" required hint="Generated automatically; edit only when required."><div className="input-prefix"><span>/</span><input placeholder="servo-rotogravure-printing-machine"/></div></Field><Field label="Product category" required><select defaultValue=""><option value="" disabled>Select category</option><option>Rotogravure Printing Machine</option><option>MLS Rotogravure Printing Machine</option><option>Shafted Rotogravure Machine</option><option>Shaftless Rotogravure Machine</option><option>Pharmaceutical Foil Machine</option></select></Field><Field label="Product group"><select defaultValue=""><option value="" disabled>Select product group</option><option>Printing Machines</option><option>Converting Machines</option><option>Flexible Packaging</option></select></Field></div></section>
   <section className="form-card"><div className="form-card-title"><ImagePlus/><div><h3>Page banner / hero section</h3><p>The first section visitors see on the product page</p></div></div><Field label="Hero heading" required><input placeholder="High Performance Servo Rotogravure Printing Machine"/></Field><Field label="Hero subheading"><textarea rows="2" placeholder="Add a concise value proposition for this product..."/></Field><div className="upload-box"><ImagePlus/><b>Upload banner image</b><span>Recommended 1920 × 720 px · JPG, PNG or WebP</span><button className="btn secondary"><Upload/> Choose image</button><input type="file" accept="image/*"/></div></section>
   <section className="form-card"><div className="form-card-title"><AlignLeft/><div><h3>Product description</h3><p>Use the Image button to upload JPG, PNG, GIF or WebP from your computer</p></div></div><Editor tinymceScriptSrc="/tinymce/tinymce.min.js" licenseKey="gpl" value={description} onEditorChange={setDescription} init={{license_key:'gpl',height:430,menubar:'file edit view insert format tools table help',plugins:'advlist anchor autolink charmap code codesample directionality emoticons fullscreen help image insertdatetime link lists media nonbreaking pagebreak preview quickbars save searchreplace table visualblocks visualchars wordcount',toolbar:'undo redo | image media link | blocks fontfamily fontsize | bold italic underline strikethrough | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table blockquote codesample | removeformat code fullscreen preview',toolbar_mode:'wrap',branding:false,promotion:false,placeholder:'Write a detailed product description and upload images...',automatic_uploads:true,image_advtab:true,image_caption:true,image_title:true,object_resizing:'img',images_file_types:'jpg,jpeg,png,gif,webp',images_upload_handler:blobInfo=>Promise.resolve(`data:${blobInfo.blob().type};base64,${blobInfo.base64()}`),file_picker_types:'file image media',file_picker_callback:(callback,_value,meta)=>{const input=document.createElement('input');input.type='file';input.accept=meta.filetype==='image'?'image/jpeg,image/png,image/gif,image/webp':meta.filetype==='media'?'video/*,audio/*':'*/*';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>callback(reader.result,{title:file.name,alt:file.name});reader.readAsDataURL(file)};input.click()},content_style:'body{font-family:DM Sans,Arial,sans-serif;font-size:14px;line-height:1.65;padding:8px 12px} img{max-width:100%;height:auto} figure.image{margin:1em auto;text-align:center} figure.image figcaption{color:#667;font-size:12px}',quickbars_selection_toolbar:'bold italic | quicklink h2 h3 blockquote',quickbars_insert_toolbar:'quickimage quicktable'}}/></section>
   <section className="form-card"><div className="form-card-title"><Settings2/><div><h3>Technical specifications</h3><p>Add unlimited specification rows</p></div><button className="section-add" onClick={addSpec}><Plus/> Add row</button></div><div className="dynamic-list">{specs.map((s,i)=><div className="dynamic-row" key={i}><GripVertical/><input value={s.name} onChange={e=>updateSpec(i,'name',e.target.value)} placeholder="Specification name"/><input value={s.value} onChange={e=>updateSpec(i,'value',e.target.value)} placeholder="Value / unit"/><button onClick={()=>removeSpec(i)}><Trash2/></button></div>)}</div></section>
   <section className="form-card"><div className="form-card-title"><CircleHelp/><div><h3>Frequently asked questions <span className="optional">Optional</span></h3><p>Helpful questions shown on the product page</p></div><button className="section-add" onClick={addFaq}><Plus/> Add FAQ</button></div>{faqs.map((f,i)=><div className="faq-edit" key={i}><div><b>FAQ {i+1}</b><button onClick={()=>setFaqs(faqs.filter((_,n)=>n!==i))}><Trash2/></button></div><input value={f.question} onChange={e=>updateFaq(i,'question',e.target.value)} placeholder="Question"/><textarea value={f.answer} onChange={e=>updateFaq(i,'answer',e.target.value)} rows="3" placeholder="Answer"/></div>)}</section>
  </div><aside className="form-aside"><section className="form-card sticky-card"><div className="form-card-title small"><GlobeIcon/><div><h3>Publishing</h3></div></div><Field label="Website" required><select><option>Mohindra Mechanical Works</option></select></Field><Field label="Status"><select><option>Draft</option><option>Published</option><option>Archived</option></select></Field><Field label="Visibility"><select><option>Public</option><option>Private</option></select></Field><div className="publish-note"><Check/><span>Product URL and sitemap entry will be generated after publishing.</span></div></section></aside></div>}
  {tab==='media'&&<div className="tab-single"><section className="form-card"><div className="form-card-title"><ImagePlus/><div><h3>Product images</h3><p>Upload featured image and product gallery</p></div></div><div className="media-grid"><div className="upload-box"><ImagePlus/><b>Featured image</b><span>Square or 4:3 WebP recommended</span><input type="file" accept="image/*"/></div><div className="upload-box"><ImagesIcon/><b>Product gallery</b><span>Upload multiple product images</span><input type="file" accept="image/*" multiple/></div></div></section><ProductCards/><section className="form-card"><div className="form-card-title"><Video/><div><h3>Machine video section</h3><p>Embed a product demonstration video on the detail page</p></div></div><Field label="Section heading"><input placeholder="Watch Our Machines in Operation"/></Field><Field label="YouTube URL"><input type="url" placeholder="https://www.youtube.com/watch?v=..."/></Field><div className="upload-box compact"><Video/><b>Video thumbnail</b><span>Upload a custom preview image</span><input type="file" accept="image/*"/></div></section><section className="form-card"><div className="form-card-title"><FileText/><div><h3>Product brochure</h3><p>Upload a downloadable PDF brochure</p></div></div><div className="upload-box compact"><Upload/><b>Upload brochure</b><span>PDF up to 15 MB</span><input type="file" accept="application/pdf"/></div></section></div>}
  {tab==='seo'&&<div className="seo-layout"><div className="tab-single">
   <section className="form-card"><div className="form-card-title"><Search/><div><h3>Search appearance</h3><p>Metadata shown on Google and other search engines</p></div></div><Field label="Focus keyword" hint="Use one primary phrase naturally in the title, description and content."><input placeholder="e.g. rotogravure printing machine manufacturer"/></Field><Field label="SEO title" required hint="Recommended length: 45–60 characters."><input placeholder="Product Name | Mohindra Mechanical Works" maxLength="60"/></Field><Field label="Meta description" required hint="Recommended length: 120–160 characters."><textarea rows="4" maxLength="160" placeholder="Write a clear, factual summary of this product..."/></Field><Field label="Meta keywords"><input placeholder="rotogravure machine, printing machine, manufacturer"/></Field><Field label="Canonical URL" required hint="Use the final preferred product URL to prevent duplicate indexing."><input type="url" placeholder="https://your-domain.com/category/product/"/></Field><div className="form-grid two"><Field label="Search indexing"><select defaultValue="index"><option value="index">Index — allow search engines</option><option value="noindex">NoIndex — hide from search</option></select></Field><Field label="Link following"><select defaultValue="follow"><option value="follow">Follow links</option><option value="nofollow">NoFollow links</option></select></Field></div></section>
   <section className="form-card"><div className="form-card-title"><Share2/><div><h3>Social sharing / Open Graph</h3><p>Control product preview on WhatsApp, Facebook and LinkedIn</p></div></div><Field label="OG title"><input maxLength="60" placeholder="Social sharing title"/></Field><Field label="OG description"><textarea rows="3" maxLength="160" placeholder="Social sharing description"/></Field><div className="upload-box compact"><ImagePlus/><b>Upload OG image</b><span>Recommended 1200 × 630 px</span><input type="file" accept="image/*"/></div></section>
   <section className="form-card"><div className="form-card-title"><Code2/><div><h3>Structured data</h3><p>Valid Schema.org information generated from saved product data</p></div></div><div className="form-grid two"><Field label="Schema type"><select><option>Product</option></select></Field><Field label="Brand"><input placeholder="Mohindra Mechanical Works"/></Field></div><Field label="Featured image alt text" required><input placeholder="Describe the actual machine visible in the image"/></Field><div className="schema-note"><Check/><p><b>Safe Product schema</b><span>Price, rating, reviews and availability will not be generated unless real values are provided.</span></p></div></section>
  </div><aside className="seo-aside"><section className="form-card seo-audit-card"><div className="form-card-title small"><BarChart3/><div><h3>SEO readiness</h3><p>Product page checklist</p></div></div><div className="seo-meter"><strong>78</strong><span>/100</span><div><i style={{width:'78%'}}/></div></div><ul className="seo-checks"><li className="good"><Check/> Index and Follow enabled</li><li className="good"><Check/> Clean product URL</li><li className="warning"><CircleHelp/> Add SEO title</li><li className="warning"><CircleHelp/> Add meta description</li><li className="warning"><CircleHelp/> Add canonical URL</li><li className="warning"><CircleHelp/> Add image alt text</li></ul><div className="index-note"><Search/><p><b>Indexing reminder</b><span>Only published products marked Index will appear in the website sitemap.</span></p></div></section><section className="form-card serp-card"><small>GOOGLE PREVIEW</small><a>Product Name | Mohindra Mechanical Works</a><em>https://your-domain.com/category/product/</em><p>Your product meta description will appear here after you enter it.</p></section></aside></div>}
 </div>
}
function GlobeIcon(){return <FolderTree/>}function ImagesIcon(){return <Boxes/>}
