import React, { useEffect, useState } from "react";
import { Edit3, Plus, Save, UserPlus, X } from "lucide-react";
import { api } from "./api.js";
export default function UserManager({ sites = [], notify = () => {} }) {
  const blank = { name: "", email: "", password: "", role: "editor", status: "active", websiteIds: [] };
  const [users, setUsers] = useState([]), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false);
  const load = () => api("/api/users").then(({ data }) => setUsers(data)).catch((e) => notify("Could not load users", e.message)); useEffect(load, []);
  const change = (key, value) => setForm((x) => ({ ...x, [key]: value }));
  const begin = (user = null) => { setEditing(user); setForm(user ? { ...blank, ...user, password: "", websiteIds: (user.websiteIds || []).map(String) } : blank); setOpen(true); };
  async function save() { try { await api(`/api/users${editing ? `/${editing._id}` : ""}`, { method: editing ? "PUT" : "POST", body: JSON.stringify(form) }); notify("User saved", form.email); setOpen(false); load(); } catch (e) { notify("Could not save user", e.message); } }
  return <div className="website-page animate-in"><div className="form-page-head"><div><p className="eyebrow">ACCESS CONTROL</p><h1>Users & Roles</h1><p>Assign Admin or Editor access to specific websites.</p></div><button className="btn primary" onClick={() => begin()}><Plus /> Add user</button></div><section className="panel"><div className="category-records">{users.map((u) => <article key={u._id}><span className="main"><UserPlus /></span><div><b>{u.name}</b><small>{u.email} · {u.role.replace("_", " ")} · {u.status}</small></div><button onClick={() => begin(u)}><Edit3 /></button></article>)}</div></section>{open && <div className="modal-backdrop open"><div className="modal modal-pop website-modal"><button className="modal-close" onClick={() => setOpen(false)}><X /></button><h3>{editing ? "Edit user" : "Add user"}</h3><label className="form-field"><span>Name</span><input value={form.name} onChange={(e) => change("name", e.target.value)} /></label><label className="form-field"><span>Email</span><input type="email" value={form.email} onChange={(e) => change("email", e.target.value)} /></label><label className="form-field"><span>{editing ? "New password (optional)" : "Password (minimum 12 characters)"}</span><input type="password" value={form.password} onChange={(e) => change("password", e.target.value)} /></label><label className="form-field"><span>Role</span><select value={form.role} onChange={(e) => change("role", e.target.value)}><option value="admin">Admin</option><option value="editor">Editor / Client</option><option value="super_admin">Super Admin</option></select></label><label className="form-field"><span>Assigned websites</span><select multiple value={form.websiteIds} onChange={(e) => change("websiteIds", [...e.target.selectedOptions].map((o) => o.value))}>{sites.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><small>Ctrl/Cmd click to select multiple websites.</small></label><label className="form-field"><span>Status</span><select value={form.status} onChange={(e) => change("status", e.target.value)}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><div className="modal-actions"><button className="btn secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn primary" onClick={save}><Save /> Save user</button></div></div></div>}</div>;
}
