import React,{useState}from'react';
import{Globe2,Plus,ExternalLink,Settings,CheckCircle2,MoreHorizontal,X}from'lucide-react';
export const websites=[{id:'all',name:'All Websites',domain:'Combined overview',initial:'A'},{id:'mmw',name:'Mohindra Mechanical Works',domain:'mohindramechanical.com',initial:'M'},{id:'rotogravure',name:'Rotogravure Machines',domain:'rotogravure.mohindramechanical.com',initial:'R'},{id:'packaging',name:'Packaging Machines',domain:'packaging.mohindramechanical.com',initial:'P'}];
export default function WebsiteManager({selected,onSelect,onNotify=()=>{}}){
 const[adding,setAdding]=useState(false),[name,setName]=useState(''),[domain,setDomain]=useState(''),[domainType,setDomainType]=useState('main'),[subdomain,setSubdomain]=useState('');
 const finalDomain=domainType==='subdomain'&&subdomain?`${subdomain}.${domain}`:domain;
 function create(){onNotify('Website created',`${name} · ${finalDomain}`);setAdding(false);setName('');setDomain('');setSubdomain('');setDomainType('main')}
 return <div className="website-page animate-in"><div className="form-page-head"><div><p className="eyebrow">MULTI-WEBSITE CMS</p><h1>Websites</h1><p>Manage main domains and subdomains from one panel.</p></div><button className="btn primary" onClick={()=>setAdding(true)}><Plus/> Add website</button></div><div className="tenant-banner"><Globe2/><div><b>Content isolation is active</b><span>Each main domain or subdomain keeps its own products, pages, SEO and media.</span></div></div><div className="website-grid">{websites.filter(w=>w.id!=='all').map(w=><article className={`website-card ${selected.id===w.id?'selected':''}`} key={w.id}><div className="website-card-head"><span>{w.initial}</span><div><h3>{w.name}</h3><p>{w.domain}</p></div><MoreHorizontal/></div><div className="website-status"><span><CheckCircle2/> Active</span><em>{w.id==='mmw'?'Main domain':'Subdomain'}</em></div><div className="website-actions"><button onClick={()=>onSelect(w)}><CheckCircle2/> Select</button><button onClick={()=>onNotify('Website settings',`${w.name} settings opened.`)}><Settings/> Settings</button><button onClick={()=>onNotify('Website preview',`https://${w.domain}`)}><ExternalLink/></button></div></article>)}</div>{adding&&<div className="modal-backdrop open"><div className="modal modal-pop website-modal"><button className="modal-close" onClick={()=>setAdding(false)}><X/></button><span className="modal-icon"><Globe2/></span><h3>Add new website</h3><p>Choose whether this website uses a main domain or a subdomain.</p><label className="form-field"><span>Website name *</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Packaging Machines"/></label><div className="domain-type"><button type="button" className={domainType==='main'?'active':''} onClick={()=>setDomainType('main')}><Globe2/><b>Main domain</b><small>example.com</small></button><button type="button" className={domainType==='subdomain'?'active':''} onClick={()=>setDomainType('subdomain')}><ExternalLink/><b>Subdomain</b><small>shop.example.com</small></button></div>{domainType==='subdomain'&&<label className="form-field"><span>Subdomain *</span><input value={subdomain} onChange={e=>setSubdomain(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} placeholder="packaging"/><small>Prefix only—do not enter a dot.</small></label>}<label className="form-field"><span>{domainType==='main'?'Main domain':'Parent domain'} *</span><input value={domain} onChange={e=>setDomain(e.target.value.toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,''))} placeholder="mohindramechanical.com"/>{finalDomain&&<small>Final address: https://{finalDomain}</small>}</label><div className="modal-actions"><button className="btn secondary" onClick={()=>setAdding(false)}>Cancel</button><button className="btn primary" disabled={!name||!domain||(domainType==='subdomain'&&!subdomain)} onClick={create}>Create website</button></div></div></div>}</div>
}
