import React, { useEffect, useState } from "react";
import { Building2, Globe2, Image, LayoutTemplate, Palette, Save, Share2 } from "lucide-react";
import { api } from "./api.js";

const Field = ({ label, children }) => <label className="form-field"><span>{label}</span>{children}</label>;

export default function WebsiteSettingsAdvanced({ website, onUpdated = () => {}, notify = () => {} }) {
  const [form, setForm] = useState(website || {});
  useEffect(() => setForm(website || {}), [website?.id, website?._id]);
  const change = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const nested = (group, key, value) => change(group, { ...(form[group] || {}), [key]: value });
  const readImage = (file, key) => { if (!file) return; if (file.size > 3 * 1024 * 1024) return notify("File too large", "Maximum size is 3 MB."); const reader = new FileReader(); reader.onload = () => change(key, String(reader.result)); reader.readAsDataURL(file); };
  async function save() {
    try {
      const payload = { name: form.name, domain: form.domain, email: form.email, phone: form.phone, address: form.address, logo: form.logo, favicon: form.favicon, socialLinks: form.socialLinks, headerSettings: form.headerSettings, footerSettings: form.footerSettings, themeSettings: form.themeSettings, seo: form.seo };
      const { data } = await api(`/api/websites/${website._id || website.id}`, { method: "PUT", body: JSON.stringify(payload) });
      onUpdated({ ...data, id: data._id, initial: data.name.charAt(0) }); notify("Settings saved", data.name);
    } catch (e) { notify("Could not save settings", e.message); }
  }
  return <div className="website-page animate-in settings-workspace">
    <div className="form-page-head"><div><p className="eyebrow">WEBSITE CONFIGURATION</p><h1>Website Settings</h1><p>Branding, contact details and frontend defaults can be edited in one place.</p></div><button className="btn primary" onClick={save}><Save /> Save all settings</button></div>
    <section className="form-card"><div className="form-card-title"><Building2 /><div><h3>Website identity</h3><p>CMS aur public website ki basic information.</p></div></div><div className="form-grid two"><Field label="Website name"><input value={form.name || ""} onChange={(e) => change("name", e.target.value)} /></Field><Field label="Domain"><input value={form.domain || ""} onChange={(e) => change("domain", e.target.value)} /></Field><Field label="Email"><input type="email" value={form.email || ""} onChange={(e) => change("email", e.target.value)} /></Field><Field label="Phone / WhatsApp"><input value={form.phone || ""} onChange={(e) => change("phone", e.target.value)} /></Field></div><Field label="Address"><textarea rows="3" value={form.address || ""} onChange={(e) => change("address", e.target.value)} /></Field></section>
    <section className="form-card"><div className="form-card-title"><Image /><div><h3>Logo & browser icon</h3><p>You can preview the current files and replace them.</p></div></div><div className="settings-brand-grid"><label className="settings-image-upload"><b>Website logo</b>{form.logo ? <img src={form.logo} alt="Website logo" /> : <Image />}<input type="file" accept="image/*" onChange={(e) => readImage(e.target.files?.[0], "logo")} /><span>Choose logo</span></label><label className="settings-image-upload"><b>Favicon</b>{form.favicon ? <img src={form.favicon} alt="Favicon" /> : <Globe2 />}<input type="file" accept="image/png,image/x-icon,image/svg+xml" onChange={(e) => readImage(e.target.files?.[0], "favicon")} /><span>Choose favicon</span></label></div></section>
    <section className="form-card"><div className="form-card-title"><LayoutTemplate /><div><h3>Header & footer</h3><p>Frontend buttons aur footer text.</p></div></div><div className="form-grid two"><Field label="Header enquiry button text"><input value={form.headerSettings?.enquiryText || ""} onChange={(e) => nested("headerSettings", "enquiryText", e.target.value)} placeholder="Get In Touch" /></Field><Field label="WhatsApp button text"><input value={form.headerSettings?.whatsappText || ""} onChange={(e) => nested("headerSettings", "whatsappText", e.target.value)} placeholder="WhatsApp Now" /></Field><Field label="Footer company text"><textarea rows="3" value={form.footerSettings?.about || ""} onChange={(e) => nested("footerSettings", "about", e.target.value)} /></Field><Field label="Copyright text"><textarea rows="3" value={form.footerSettings?.copyright || ""} onChange={(e) => nested("footerSettings", "copyright", e.target.value)} /></Field></div></section>
    <section className="form-card"><div className="form-card-title"><Share2 /><div><h3>Social links</h3><p>Blank links will not be shown on the frontend.</p></div></div><div className="form-grid two">{["facebook","instagram","youtube","linkedin"].map((key) => <Field label={key.charAt(0).toUpperCase() + key.slice(1)} key={key}><input type="url" value={form.socialLinks?.[key] || ""} onChange={(e) => nested("socialLinks", key, e.target.value)} placeholder={`https://${key}.com/...`} /></Field>)}</div></section>
    <section className="form-card"><div className="form-card-title"><Palette /><div><h3>Theme colours</h3><p>Website ke primary colours.</p></div></div><div className="form-grid two"><Field label="Primary colour"><input type="color" value={form.themeSettings?.primaryColor || "#c8102e"} onChange={(e) => nested("themeSettings", "primaryColor", e.target.value)} /></Field><Field label="Secondary colour"><input type="color" value={form.themeSettings?.secondaryColor || "#123f73"} onChange={(e) => nested("themeSettings", "secondaryColor", e.target.value)} /></Field></div></section>
    <section className="form-card"><div className="form-card-title"><Globe2 /><div><h3>Default website SEO</h3><p>Product SEO is set separately in the Add Product SEO tab.</p></div></div><Field label="Default SEO title"><input value={form.seo?.title || ""} maxLength="60" onChange={(e) => nested("seo", "title", e.target.value)} /></Field><Field label="Default meta description"><textarea rows="3" maxLength="160" value={form.seo?.description || ""} onChange={(e) => nested("seo", "description", e.target.value)} /></Field><Field label="Default keywords"><input value={(form.seo?.keywords || []).join(", ")} onChange={(e) => nested("seo", "keywords", e.target.value.split(",").map((x) => x.trim()).filter(Boolean))} placeholder="printing machine, manufacturer" /></Field></section>
  </div>;
}
