import React, { useEffect, useState } from "react";
import { CheckCircle2, Edit3, Save, Search, Settings, X } from "lucide-react";
import { api } from "./api.js";

export function SeoManager({ website, notify = () => {} }) {
  const id = website?._id || website?.id, headers = { "x-website-id": id };
  const [products, setProducts] = useState([]), [editing, setEditing] = useState(null);
  const load = () => api("/api/products?limit=100", { headers }).then(({ data }) => setProducts(data)).catch((e) => notify("SEO audit failed", e.message));
  useEffect(load, [id]);
  const score = (p) => [p.seo?.title, p.seo?.description, p.seo?.canonical, p.seo?.focusKeyword, p.shortDescription].filter(Boolean).length * 20;
  const change = (key, value) => setEditing((p) => ({ ...p, seo: { ...p.seo, [key]: value } }));
  async function save() { try { await api(`/api/products/${editing._id}`, { method: "PUT", headers, body: JSON.stringify({ seo: editing.seo }) }); notify("SEO saved", editing.name); setEditing(null); load(); } catch (e) { notify("Could not save SEO", e.message); } }
  return <div className="website-page animate-in"><div className="form-page-head"><div><p className="eyebrow">TECHNICAL SEO</p><h1>SEO Manager</h1><p>Edit product metadata, canonical URLs and indexing for {website.name}.</p></div><div className="form-head-actions"><a className="btn secondary" href={`/api/public/robots.txt?domain=${website.domain}`} target="_blank">Robots.txt</a><a className="btn secondary" href={`/api/public/sitemap.xml?domain=${website.domain}`} target="_blank"><Search /> Sitemap</a></div></div><div className="tenant-banner"><Search /><div><b>SEO workflow</b><span>Edit product → complete title, description, keyword and canonical → publish → submit sitemap in Google Search Console.</span></div></div><section className="panel"><div className="category-records">{products.map((p) => <article key={p._id}><span className="main"><CheckCircle2 /></span><div><b>{p.name}</b><small>SEO {score(p)}/100 · {p.status} · {p.seo?.index === false ? "noindex" : "index"}</small></div><strong className={`seo-score ${score(p) < 80 ? "mid" : ""}`}>{score(p)}/100</strong><button onClick={() => setEditing(p)}><Edit3 /></button></article>)}{!products.length && <p className="empty-state">Add a product to begin its SEO audit.</p>}</div></section>{editing && <div className="modal-backdrop open"><div className="modal modal-pop website-modal"><button className="modal-close" onClick={() => setEditing(null)}><X /></button><h3>Edit product SEO</h3><p>{editing.name}</p><label className="form-field"><span>Focus keyword</span><input value={editing.seo?.focusKeyword || ""} onChange={(e) => change("focusKeyword", e.target.value)} /></label><label className="form-field"><span>SEO title (45–60 characters)</span><input maxLength="60" value={editing.seo?.title || ""} onChange={(e) => change("title", e.target.value)} /></label><label className="form-field"><span>Meta description (120–160 characters)</span><textarea rows="4" maxLength="160" value={editing.seo?.description || ""} onChange={(e) => change("description", e.target.value)} /></label><label className="form-field"><span>Canonical URL</span><input type="url" value={editing.seo?.canonical || ""} onChange={(e) => change("canonical", e.target.value)} /></label><label className="form-field"><span>Search indexing</span><select value={editing.seo?.index === false ? "noindex" : "index"} onChange={(e) => change("index", e.target.value === "index")}><option value="index">Index</option><option value="noindex">NoIndex</option></select></label><div className="modal-actions"><button className="btn secondary" onClick={() => setEditing(null)}>Cancel</button><button className="btn primary" onClick={save}><Save /> Save SEO</button></div></div></div>}</div>;
}

export function WebsiteSettings({ website, onUpdated = () => {}, notify = () => {} }) {
  const [form, setForm] = useState(website); useEffect(() => setForm(website), [website?.id]);
  const change = (key, value) => setForm((x) => ({ ...x, [key]: value }));
  async function save() { try { const { data } = await api(`/api/websites/${website._id || website.id}`, { method: "PUT", body: JSON.stringify({ name: form.name, domain: form.domain, email: form.email, phone: form.phone, address: form.address, logo: form.logo, favicon: form.favicon, seo: form.seo }) }); onUpdated({ ...data, id: data._id, initial: data.name.charAt(0) }); notify("Settings saved", data.name); } catch (e) { notify("Could not save settings", e.message); } }
  return <div className="website-page animate-in"><div className="form-page-head"><div><p className="eyebrow">WEBSITE CONFIGURATION</p><h1>Settings</h1><p>Contact information, branding and site-wide SEO defaults.</p></div><button className="btn primary" onClick={save}><Save /> Save settings</button></div><section className="form-card"><div className="form-card-title"><Settings /><div><h3>Website identity</h3><p>Used by the CMS and public integration.</p></div></div><div className="form-grid two"><label className="form-field"><span>Website name</span><input value={form.name || ""} onChange={(e) => change("name", e.target.value)} /></label><label className="form-field"><span>Domain</span><input value={form.domain || ""} onChange={(e) => change("domain", e.target.value)} /></label><label className="form-field"><span>Email</span><input type="email" value={form.email || ""} onChange={(e) => change("email", e.target.value)} /></label><label className="form-field"><span>Phone</span><input value={form.phone || ""} onChange={(e) => change("phone", e.target.value)} /></label></div><label className="form-field"><span>Address</span><textarea rows="3" value={form.address || ""} onChange={(e) => change("address", e.target.value)} /></label><label className="form-field"><span>Default SEO title</span><input value={form.seo?.title || ""} onChange={(e) => change("seo", { ...form.seo, title: e.target.value })} /></label><label className="form-field"><span>Default meta description</span><textarea rows="3" value={form.seo?.description || ""} onChange={(e) => change("seo", { ...form.seo, description: e.target.value })} /></label></section></div>;
}
